//
// Created by james on 9/11/23.
//

#pragma once

#include <ut/math.hpp>

namespace game::layout
{
    struct CombatRow
    {
        ut::rect bounds;
        ut::rect score;
        ut::rect buff;
        ut::rect nerf;
        ut::rect units;

        void layout(ut::rect const& b);
        void drawDebug();
    };

    struct PlayerRow
    {
        ut::rect bounds;
        ut::rect hand;
        ut::rect deck;
        ut::rect yard;
        ut::rect lead;

        void layout(ut::rect const& b);
        void drawDebug();
    };

//    struct WeatherBoard
//    {
//        ut::rect bounds;
//
//        void layout(ut::rect const& b);
//        void drawDebug();
//    };

    struct StatsBoard
    {
        ut::rect bounds;

        ut::rect name;
        ut::rect deck_name;
        ut::rect lead_name;
        ut::rect gems;
        ut::rect score;
        ut::rect avatar;

        void layout(ut::rect const& b);
        void drawDebug();
    };

    struct GameBoard
    {
        struct Player
        {
            ut::rect bounds;

            CombatRow   siege;
            CombatRow   ranged;
            CombatRow   melee;
            PlayerRow   player;
            StatsBoard  stats;
        };

        ut::rect bounds;

        Player usr, cpu;

        void layout(ut::rect const& b);
        void drawDebug();

    };

    struct CardPicker
    {
        ut::rect bounds;

        ut::rect title;
        ut::rect cards;
        ut::rect confirm;
        ut::rect cancel;

        CardPicker()
        {
            reset();
        }

        void reset()
        {
            // *** auto-generated by ledit ***
            cancel  = ut::rect( 645.000f,  537.333f,  977.600f,  604.000f);
            cards   = ut::rect( 235.400f,  259.667f, 1044.600f,  460.333f);
            confirm = ut::rect( 302.400f,  537.333f,  635.000f,  604.000f);
            title   = ut::rect( 275.400f,   89.000f, 1004.600f,  209.667f);
            // *** auto-generated by ledit ***
        }
    };
}
