//
// Created by james on 9/11/23.
//

#pragma once

#include "layout/layout_box.hpp"

namespace game_layout
{


    struct CombatRow
    {
        ut::rect bounds;
        ut::rect score;
        ut::rect buff;
        ut::rect nerf;
        ut::rect units;

        void layout(ut::rect const& b);
        void drawDebug();
    };

    struct PlayerRow
    {
        ut::rect bounds;
        ut::rect hand;
        ut::rect deck;
        ut::rect yard;
        ut::rect lead;

        void layout(ut::rect const& b);
        void drawDebug();
    };

//    struct WeatherBoard
//    {
//        ut::rect bounds;
//
//        void layout(ut::rect const& b);
//        void drawDebug();
//    };

    struct StatsBoard
    {
        ut::rect bounds;

        ut::rect name;
        ut::rect deck_name;
        ut::rect lead_name;
        ut::rect gems;
        ut::rect score;
        ut::rect avatar;

        void layout(ut::rect const& b);
        void drawDebug();
    };

    struct GameBoard
    {
        struct Player
        {
            ut::rect bounds;

            CombatRow   siege;
            CombatRow   ranged;
            CombatRow   melee;
            PlayerRow   player;
            StatsBoard  stats;
        };

        ut::rect bounds;

        Player usr, cpu;

        void layout(ut::rect const& b);
        void drawDebug();

    };

    struct CardPicker
    {
        layout::LayoutBox title;
        layout::LayoutBox background;
        layout::LayoutBox card_choice;
        layout::LayoutBox card_options;
        layout::LayoutBox confirm;
        layout::LayoutBox cancel;

        CardPicker()
        {
            reset();
        }

        void reset()
        {
// *** auto-generated by ledit ***
            background.outer         = ut::rect(   0.000f,    0.000f, 1280.000f,  720.000f);
            background.border        = ut::rect(   0.000f,    0.000f, 1280.000f,  720.000f);
            background.inner         = ut::rect(   0.000f,    0.000f, 1280.000f,  720.000f);
            cancel.outer             = ut::rect( 645.000f,  566.080f, 1020.530f,  640.000f);
            cancel.border            = ut::rect( 645.000f,  566.080f, 1020.530f,  640.000f);
            cancel.inner             = ut::rect( 655.000f,  576.080f, 1010.530f,  630.000f);
            card_choice.outer        = ut::rect( 950.205f,  273.920f, 1100.530f,  446.080f);
            card_choice.border       = ut::rect( 950.205f,  273.920f, 1100.530f,  446.080f);
            card_choice.inner        = ut::rect( 950.205f,  273.920f, 1100.530f,  446.080f);
            card_options.outer       = ut::rect( 179.470f,  273.920f,  940.205f,  446.080f);
            card_options.border      = ut::rect( 179.470f,  273.920f,  940.205f,  446.080f);
            card_options.inner       = ut::rect( 179.470f,  273.920f,  940.205f,  446.080f);
            confirm.outer            = ut::rect( 259.470f,  566.080f,  635.000f,  640.000f);
            confirm.border           = ut::rect( 259.470f,  566.080f,  635.000f,  640.000f);
            confirm.inner            = ut::rect( 269.470f,  576.080f,  625.000f,  630.000f);
            title.outer              = ut::rect( 179.470f,    0.000f, 1100.530f,  233.920f);
            title.border             = ut::rect( 239.470f,   60.000f, 1040.530f,  173.920f);
            title.inner              = ut::rect( 254.470f,   75.000f, 1025.530f,  158.920f);
// *** auto-generated by ledit ***

        }
    };
}
