//
// Created by james on 10/10/23.
//

#include "id_bip0039.hpp"
using namespace bip0039;

//
// ut
//
#include <ut/random.hpp>
using namespace ut;

//
// std
//
#include <optional>
using namespace std;

wordlist_t& ::bip0039::wordlist()
{
    static array<cstrview, 2048> ids
    {
    "abandon"_sv, "ability"_sv, "able"_sv, "about"_sv, "above"_sv, "absent"_sv, "absorb"_sv, "abstract"_sv,
    "absurd"_sv, "abuse"_sv, "access"_sv, "accident"_sv, "account"_sv, "accuse"_sv, "achieve"_sv, "acid"_sv,
    "acoustic"_sv, "acquire"_sv, "across"_sv, "act"_sv, "action"_sv, "actor"_sv, "actress"_sv, "actual"_sv, "adapt"_sv,
    "add"_sv, "addict"_sv, "address"_sv, "adjust"_sv, "admit"_sv, "adult"_sv, "advance"_sv, "advice"_sv, "aerobic"_sv,
    "affair"_sv, "afford"_sv, "afraid"_sv, "again"_sv, "age"_sv, "agent"_sv, "agree"_sv, "ahead"_sv, "aim"_sv,
    "air"_sv, "airport"_sv, "aisle"_sv, "alarm"_sv, "album"_sv, "alcohol"_sv, "alert"_sv, "alien"_sv, "all"_sv,
    "alley"_sv, "allow"_sv, "almost"_sv, "alone"_sv, "alpha"_sv, "already"_sv, "also"_sv, "alter"_sv, "always"_sv,
    "amateur"_sv, "amazing"_sv, "among"_sv, "amount"_sv, "amused"_sv, "analyst"_sv, "anchor"_sv, "ancient"_sv,
    "anger"_sv, "angle"_sv, "angry"_sv, "animal"_sv, "ankle"_sv, "announce"_sv, "annual"_sv, "another"_sv, "answer"_sv,
    "antenna"_sv, "antique"_sv, "anxiety"_sv, "any"_sv, "apart"_sv, "apology"_sv, "appear"_sv, "apple"_sv,
    "approve"_sv, "april"_sv, "arch"_sv, "arctic"_sv, "area"_sv, "arena"_sv, "argue"_sv, "arm"_sv, "armed"_sv,
    "armor"_sv, "army"_sv, "around"_sv, "arrange"_sv, "arrest"_sv, "arrive"_sv, "arrow"_sv, "art"_sv, "artefact"_sv,
    "artist"_sv, "artwork"_sv, "ask"_sv, "aspect"_sv, "assault"_sv, "asset"_sv, "assist"_sv, "assume"_sv, "asthma"_sv,
    "athlete"_sv, "atom"_sv, "attack"_sv, "attend"_sv, "attitude"_sv, "attract"_sv, "auction"_sv, "audit"_sv,
    "august"_sv, "aunt"_sv, "author"_sv, "auto"_sv, "autumn"_sv, "average"_sv, "avocado"_sv, "avoid"_sv, "awake"_sv,
    "aware"_sv, "away"_sv, "awesome"_sv, "awful"_sv, "awkward"_sv, "axis"_sv, "baby"_sv, "bachelor"_sv, "bacon"_sv,
    "badge"_sv, "bag"_sv, "balance"_sv, "balcony"_sv, "ball"_sv, "bamboo"_sv, "banana"_sv, "banner"_sv, "bar"_sv,
    "barely"_sv, "bargain"_sv, "barrel"_sv, "base"_sv, "basic"_sv, "basket"_sv, "battle"_sv, "beach"_sv, "bean"_sv,
    "beauty"_sv, "because"_sv, "become"_sv, "beef"_sv, "before"_sv, "begin"_sv, "behave"_sv, "behind"_sv, "believe"_sv,
    "below"_sv, "belt"_sv, "bench"_sv, "benefit"_sv, "best"_sv, "betray"_sv, "better"_sv, "between"_sv, "beyond"_sv,
    "bicycle"_sv, "bid"_sv, "bike"_sv, "bind"_sv, "biology"_sv, "bird"_sv, "birth"_sv, "bitter"_sv, "black"_sv,
    "blade"_sv, "blame"_sv, "blanket"_sv, "blast"_sv, "bleak"_sv, "bless"_sv, "blind"_sv, "blood"_sv, "blossom"_sv,
    "blouse"_sv, "blue"_sv, "blur"_sv, "blush"_sv, "board"_sv, "boat"_sv, "body"_sv, "boil"_sv, "bomb"_sv, "bone"_sv,
    "bonus"_sv, "book"_sv, "boost"_sv, "border"_sv, "boring"_sv, "borrow"_sv, "boss"_sv, "bottom"_sv, "bounce"_sv,
    "box"_sv, "boy"_sv, "bracket"_sv, "brain"_sv, "brand"_sv, "brass"_sv, "brave"_sv, "bread"_sv, "breeze"_sv,
    "brick"_sv, "bridge"_sv, "brief"_sv, "bright"_sv, "bring"_sv, "brisk"_sv, "broccoli"_sv, "broken"_sv, "bronze"_sv,
    "broom"_sv, "brother"_sv, "brown"_sv, "brush"_sv, "bubble"_sv, "buddy"_sv, "budget"_sv, "buffalo"_sv, "build"_sv,
    "bulb"_sv, "bulk"_sv, "bullet"_sv, "bundle"_sv, "bunker"_sv, "burden"_sv, "burger"_sv, "burst"_sv, "bus"_sv,
    "business"_sv, "busy"_sv, "butter"_sv, "buyer"_sv, "buzz"_sv, "cabbage"_sv, "cabin"_sv, "cable"_sv, "cactus"_sv,
    "cage"_sv, "cake"_sv, "call"_sv, "calm"_sv, "camera"_sv, "camp"_sv, "can"_sv, "canal"_sv, "cancel"_sv, "candy"_sv,
    "cannon"_sv, "canoe"_sv, "canvas"_sv, "canyon"_sv, "capable"_sv, "capital"_sv, "captain"_sv, "car"_sv, "carbon"_sv,
    "card"_sv, "cargo"_sv, "carpet"_sv, "carry"_sv, "cart"_sv, "case"_sv, "cash"_sv, "casino"_sv, "castle"_sv,
    "casual"_sv, "cat"_sv, "catalog"_sv, "catch"_sv, "category"_sv, "cattle"_sv, "caught"_sv, "cause"_sv, "caution"_sv,
    "cave"_sv, "ceiling"_sv, "celery"_sv, "cement"_sv, "census"_sv, "century"_sv, "cereal"_sv, "certain"_sv,
    "chair"_sv, "chalk"_sv, "champion"_sv, "change"_sv, "chaos"_sv, "chapter"_sv, "charge"_sv, "chase"_sv, "chat"_sv,
    "cheap"_sv, "check"_sv, "cheese"_sv, "chef"_sv, "cherry"_sv, "chest"_sv, "chicken"_sv, "chief"_sv, "child"_sv,
    "chimney"_sv, "choice"_sv, "choose"_sv, "chronic"_sv, "chuckle"_sv, "chunk"_sv, "churn"_sv, "cigar"_sv,
    "cinnamon"_sv, "circle"_sv, "citizen"_sv, "city"_sv, "civil"_sv, "claim"_sv, "clap"_sv, "clarify"_sv, "claw"_sv,
    "clay"_sv, "clean"_sv, "clerk"_sv, "clever"_sv, "click"_sv, "client"_sv, "cliff"_sv, "climb"_sv, "clinic"_sv,
    "clip"_sv, "clock"_sv, "clog"_sv, "close"_sv, "cloth"_sv, "cloud"_sv, "clown"_sv, "club"_sv, "clump"_sv,
    "cluster"_sv, "clutch"_sv, "coach"_sv, "coast"_sv, "coconut"_sv, "code"_sv, "coffee"_sv, "coil"_sv, "coin"_sv,
    "collect"_sv, "color"_sv, "column"_sv, "combine"_sv, "come"_sv, "comfort"_sv, "comic"_sv, "common"_sv,
    "company"_sv, "concert"_sv, "conduct"_sv, "confirm"_sv, "congress"_sv, "connect"_sv, "consider"_sv, "control"_sv,
    "convince"_sv, "cook"_sv, "cool"_sv, "copper"_sv, "copy"_sv, "coral"_sv, "core"_sv, "corn"_sv, "correct"_sv,
    "cost"_sv, "cotton"_sv, "couch"_sv, "country"_sv, "couple"_sv, "course"_sv, "cousin"_sv, "cover"_sv, "coyote"_sv,
    "crack"_sv, "cradle"_sv, "craft"_sv, "cram"_sv, "crane"_sv, "crash"_sv, "crater"_sv, "crawl"_sv, "crazy"_sv,
    "cream"_sv, "credit"_sv, "creek"_sv, "crew"_sv, "cricket"_sv, "crime"_sv, "crisp"_sv, "critic"_sv, "crop"_sv,
    "cross"_sv, "crouch"_sv, "crowd"_sv, "crucial"_sv, "cruel"_sv, "cruise"_sv, "crumble"_sv, "crunch"_sv, "crush"_sv,
    "cry"_sv, "crystal"_sv, "cube"_sv, "culture"_sv, "cup"_sv, "cupboard"_sv, "curious"_sv, "current"_sv, "curtain"_sv,
    "curve"_sv, "cushion"_sv, "custom"_sv, "cute"_sv, "cycle"_sv, "dad"_sv, "damage"_sv, "damp"_sv, "dance"_sv,
    "danger"_sv, "daring"_sv, "dash"_sv, "daughter"_sv, "dawn"_sv, "day"_sv, "deal"_sv, "debate"_sv, "debris"_sv,
    "decade"_sv, "december"_sv, "decide"_sv, "decline"_sv, "decorate"_sv, "decrease"_sv, "deer"_sv, "defense"_sv,
    "define"_sv, "defy"_sv, "degree"_sv, "delay"_sv, "deliver"_sv, "demand"_sv, "demise"_sv, "denial"_sv, "dentist"_sv,
    "deny"_sv, "depart"_sv, "depend"_sv, "deposit"_sv, "depth"_sv, "deputy"_sv, "derive"_sv, "describe"_sv,
    "desert"_sv, "design"_sv, "desk"_sv, "despair"_sv, "destroy"_sv, "detail"_sv, "detect"_sv, "develop"_sv,
    "device"_sv, "devote"_sv, "diagram"_sv, "dial"_sv, "diamond"_sv, "diary"_sv, "dice"_sv, "diesel"_sv, "diet"_sv,
    "differ"_sv, "digital"_sv, "dignity"_sv, "dilemma"_sv, "dinner"_sv, "dinosaur"_sv, "direct"_sv, "dirt"_sv,
    "disagree"_sv, "discover"_sv, "disease"_sv, "dish"_sv, "dismiss"_sv, "disorder"_sv, "display"_sv, "distance"_sv,
    "divert"_sv, "divide"_sv, "divorce"_sv, "dizzy"_sv, "doctor"_sv, "document"_sv, "dog"_sv, "doll"_sv, "dolphin"_sv,
    "domain"_sv, "donate"_sv, "donkey"_sv, "donor"_sv, "door"_sv, "dose"_sv, "double"_sv, "dove"_sv, "draft"_sv,
    "dragon"_sv, "drama"_sv, "drastic"_sv, "draw"_sv, "dream"_sv, "dress"_sv, "drift"_sv, "drill"_sv, "drink"_sv,
    "drip"_sv, "drive"_sv, "drop"_sv, "drum"_sv, "dry"_sv, "duck"_sv, "dumb"_sv, "dune"_sv, "during"_sv, "dust"_sv,
    "dutch"_sv, "duty"_sv, "dwarf"_sv, "dynamic"_sv, "eager"_sv, "eagle"_sv, "early"_sv, "earn"_sv, "earth"_sv,
    "easily"_sv, "east"_sv, "easy"_sv, "echo"_sv, "ecology"_sv, "economy"_sv, "edge"_sv, "edit"_sv, "educate"_sv,
    "effort"_sv, "egg"_sv, "eight"_sv, "either"_sv, "elbow"_sv, "elder"_sv, "electric"_sv, "elegant"_sv, "element"_sv,
    "elephant"_sv, "elevator"_sv, "elite"_sv, "else"_sv, "embark"_sv, "embody"_sv, "embrace"_sv, "emerge"_sv,
    "emotion"_sv, "employ"_sv, "empower"_sv, "empty"_sv, "enable"_sv, "enact"_sv, "end"_sv, "endless"_sv, "endorse"_sv,
    "enemy"_sv, "energy"_sv, "enforce"_sv, "engage"_sv, "engine"_sv, "enhance"_sv, "enjoy"_sv, "enlist"_sv,
    "enough"_sv, "enrich"_sv, "enroll"_sv, "ensure"_sv, "enter"_sv, "entire"_sv, "entry"_sv, "envelope"_sv,
    "episode"_sv, "equal"_sv, "equip"_sv, "era"_sv, "erase"_sv, "erode"_sv, "erosion"_sv, "error"_sv, "erupt"_sv,
    "escape"_sv, "essay"_sv, "essence"_sv, "estate"_sv, "eternal"_sv, "ethics"_sv, "evidence"_sv, "evil"_sv,
    "evoke"_sv, "evolve"_sv, "exact"_sv, "example"_sv, "excess"_sv, "exchange"_sv, "excite"_sv, "exclude"_sv,
    "excuse"_sv, "execute"_sv, "exercise"_sv, "exhaust"_sv, "exhibit"_sv, "exile"_sv, "exist"_sv, "exit"_sv,
    "exotic"_sv, "expand"_sv, "expect"_sv, "expire"_sv, "explain"_sv, "expose"_sv, "express"_sv, "extend"_sv,
    "extra"_sv, "eye"_sv, "eyebrow"_sv, "fabric"_sv, "face"_sv, "faculty"_sv, "fade"_sv, "faint"_sv, "faith"_sv,
    "fall"_sv, "false"_sv, "fame"_sv, "family"_sv, "famous"_sv, "fan"_sv, "fancy"_sv, "fantasy"_sv, "farm"_sv,
    "fashion"_sv, "fat"_sv, "fatal"_sv, "father"_sv, "fatigue"_sv, "fault"_sv, "favorite"_sv, "feature"_sv,
    "february"_sv, "federal"_sv, "fee"_sv, "feed"_sv, "feel"_sv, "female"_sv, "fence"_sv, "festival"_sv, "fetch"_sv,
    "fever"_sv, "few"_sv, "fiber"_sv, "fiction"_sv, "field"_sv, "figure"_sv, "file"_sv, "film"_sv, "filter"_sv,
    "final"_sv, "find"_sv, "fine"_sv, "finger"_sv, "finish"_sv, "fire"_sv, "firm"_sv, "first"_sv, "fiscal"_sv,
    "fish"_sv, "fit"_sv, "fitness"_sv, "fix"_sv, "flag"_sv, "flame"_sv, "flash"_sv, "flat"_sv, "flavor"_sv, "flee"_sv,
    "flight"_sv, "flip"_sv, "float"_sv, "flock"_sv, "floor"_sv, "flower"_sv, "fluid"_sv, "flush"_sv, "fly"_sv,
    "foam"_sv, "focus"_sv, "fog"_sv, "foil"_sv, "fold"_sv, "follow"_sv, "food"_sv, "foot"_sv, "force"_sv, "forest"_sv,
    "forget"_sv, "fork"_sv, "fortune"_sv, "forum"_sv, "forward"_sv, "fossil"_sv, "foster"_sv, "found"_sv, "fox"_sv,
    "fragile"_sv, "frame"_sv, "frequent"_sv, "fresh"_sv, "friend"_sv, "fringe"_sv, "frog"_sv, "front"_sv, "frost"_sv,
    "frown"_sv, "frozen"_sv, "fruit"_sv, "fuel"_sv, "fun"_sv, "funny"_sv, "furnace"_sv, "fury"_sv, "future"_sv,
    "gadget"_sv, "gain"_sv, "galaxy"_sv, "gallery"_sv, "game"_sv, "gap"_sv, "garage"_sv, "garbage"_sv, "garden"_sv,
    "garlic"_sv, "garment"_sv, "gas"_sv, "gasp"_sv, "gate"_sv, "gather"_sv, "gauge"_sv, "gaze"_sv, "general"_sv,
    "genius"_sv, "genre"_sv, "gentle"_sv, "genuine"_sv, "gesture"_sv, "ghost"_sv, "giant"_sv, "gift"_sv, "giggle"_sv,
    "ginger"_sv, "giraffe"_sv, "girl"_sv, "give"_sv, "glad"_sv, "glance"_sv, "glare"_sv, "glass"_sv, "glide"_sv,
    "glimpse"_sv, "globe"_sv, "gloom"_sv, "glory"_sv, "glove"_sv, "glow"_sv, "glue"_sv, "goat"_sv, "goddess"_sv,
    "gold"_sv, "good"_sv, "goose"_sv, "gorilla"_sv, "gospel"_sv, "gossip"_sv, "govern"_sv, "gown"_sv, "grab"_sv,
    "grace"_sv, "grain"_sv, "grant"_sv, "grape"_sv, "grass"_sv, "gravity"_sv, "great"_sv, "green"_sv, "grid"_sv,
    "grief"_sv, "grit"_sv, "grocery"_sv, "group"_sv, "grow"_sv, "grunt"_sv, "guard"_sv, "guess"_sv, "guide"_sv,
    "guilt"_sv, "guitar"_sv, "gun"_sv, "gym"_sv, "habit"_sv, "hair"_sv, "half"_sv, "hammer"_sv, "hamster"_sv,
    "hand"_sv, "happy"_sv, "harbor"_sv, "hard"_sv, "harsh"_sv, "harvest"_sv, "hat"_sv, "have"_sv, "hawk"_sv,
    "hazard"_sv, "head"_sv, "health"_sv, "heart"_sv, "heavy"_sv, "hedgehog"_sv, "height"_sv, "hello"_sv, "helmet"_sv,
    "help"_sv, "hen"_sv, "hero"_sv, "hidden"_sv, "high"_sv, "hill"_sv, "hint"_sv, "hip"_sv, "hire"_sv, "history"_sv,
    "hobby"_sv, "hockey"_sv, "hold"_sv, "hole"_sv, "holiday"_sv, "hollow"_sv, "home"_sv, "honey"_sv, "hood"_sv,
    "hope"_sv, "horn"_sv, "horror"_sv, "horse"_sv, "hospital"_sv, "host"_sv, "hotel"_sv, "hour"_sv, "hover"_sv,
    "hub"_sv, "huge"_sv, "human"_sv, "humble"_sv, "humor"_sv, "hundred"_sv, "hungry"_sv, "hunt"_sv, "hurdle"_sv,
    "hurry"_sv, "hurt"_sv, "husband"_sv, "hybrid"_sv, "ice"_sv, "icon"_sv, "idea"_sv, "identify"_sv, "idle"_sv,
    "ignore"_sv, "ill"_sv, "illegal"_sv, "illness"_sv, "image"_sv, "imitate"_sv, "immense"_sv, "immune"_sv,
    "impact"_sv, "impose"_sv, "improve"_sv, "impulse"_sv, "inch"_sv, "include"_sv, "income"_sv, "increase"_sv,
    "index"_sv, "indicate"_sv, "indoor"_sv, "industry"_sv, "infant"_sv, "inflict"_sv, "inform"_sv, "inhale"_sv,
    "inherit"_sv, "initial"_sv, "inject"_sv, "injury"_sv, "inmate"_sv, "inner"_sv, "innocent"_sv, "input"_sv,
    "inquiry"_sv, "insane"_sv, "insect"_sv, "inside"_sv, "inspire"_sv, "install"_sv, "intact"_sv, "interest"_sv,
    "into"_sv, "invest"_sv, "invite"_sv, "involve"_sv, "iron"_sv, "island"_sv, "isolate"_sv, "issue"_sv, "item"_sv,
    "ivory"_sv, "jacket"_sv, "jaguar"_sv, "jar"_sv, "jazz"_sv, "jealous"_sv, "jeans"_sv, "jelly"_sv, "jewel"_sv,
    "job"_sv, "join"_sv, "joke"_sv, "journey"_sv, "joy"_sv, "judge"_sv, "juice"_sv, "jump"_sv, "jungle"_sv,
    "junior"_sv, "junk"_sv, "just"_sv, "kangaroo"_sv, "keen"_sv, "keep"_sv, "ketchup"_sv, "key"_sv, "kick"_sv,
    "kid"_sv, "kidney"_sv, "kind"_sv, "kingdom"_sv, "kiss"_sv, "kit"_sv, "kitchen"_sv, "kite"_sv, "kitten"_sv,
    "kiwi"_sv, "knee"_sv, "knife"_sv, "knock"_sv, "know"_sv, "lab"_sv, "label"_sv, "labor"_sv, "ladder"_sv, "lady"_sv,
    "lake"_sv, "lamp"_sv, "language"_sv, "laptop"_sv, "large"_sv, "later"_sv, "latin"_sv, "laugh"_sv, "laundry"_sv,
    "lava"_sv, "law"_sv, "lawn"_sv, "lawsuit"_sv, "layer"_sv, "lazy"_sv, "leader"_sv, "leaf"_sv, "learn"_sv,
    "leave"_sv, "lecture"_sv, "left"_sv, "leg"_sv, "legal"_sv, "legend"_sv, "leisure"_sv, "lemon"_sv, "lend"_sv,
    "length"_sv, "lens"_sv, "leopard"_sv, "lesson"_sv, "letter"_sv, "level"_sv, "liar"_sv, "liberty"_sv, "library"_sv,
    "license"_sv, "life"_sv, "lift"_sv, "light"_sv, "like"_sv, "limb"_sv, "limit"_sv, "link"_sv, "lion"_sv,
    "liquid"_sv, "list"_sv, "little"_sv, "live"_sv, "lizard"_sv, "load"_sv, "loan"_sv, "lobster"_sv, "local"_sv,
    "lock"_sv, "logic"_sv, "lonely"_sv, "long"_sv, "loop"_sv, "lottery"_sv, "loud"_sv, "lounge"_sv, "love"_sv,
    "loyal"_sv, "lucky"_sv, "luggage"_sv, "lumber"_sv, "lunar"_sv, "lunch"_sv, "luxury"_sv, "lyrics"_sv, "machine"_sv,
    "mad"_sv, "magic"_sv, "magnet"_sv, "maid"_sv, "mail"_sv, "main"_sv, "major"_sv, "make"_sv, "mammal"_sv, "man"_sv,
    "manage"_sv, "mandate"_sv, "mango"_sv, "mansion"_sv, "manual"_sv, "maple"_sv, "marble"_sv, "march"_sv, "margin"_sv,
    "marine"_sv, "market"_sv, "marriage"_sv, "mask"_sv, "mass"_sv, "master"_sv, "match"_sv, "material"_sv, "math"_sv,
    "matrix"_sv, "matter"_sv, "maximum"_sv, "maze"_sv, "meadow"_sv, "mean"_sv, "measure"_sv, "meat"_sv, "mechanic"_sv,
    "medal"_sv, "media"_sv, "melody"_sv, "melt"_sv, "member"_sv, "memory"_sv, "mention"_sv, "menu"_sv, "mercy"_sv,
    "merge"_sv, "merit"_sv, "merry"_sv, "mesh"_sv, "message"_sv, "metal"_sv, "method"_sv, "middle"_sv, "midnight"_sv,
    "milk"_sv, "million"_sv, "mimic"_sv, "mind"_sv, "minimum"_sv, "minor"_sv, "minute"_sv, "miracle"_sv, "mirror"_sv,
    "misery"_sv, "miss"_sv, "mistake"_sv, "mix"_sv, "mixed"_sv, "mixture"_sv, "mobile"_sv, "model"_sv, "modify"_sv,
    "mom"_sv, "moment"_sv, "monitor"_sv, "monkey"_sv, "monster"_sv, "month"_sv, "moon"_sv, "moral"_sv, "more"_sv,
    "morning"_sv, "mosquito"_sv, "mother"_sv, "motion"_sv, "motor"_sv, "mountain"_sv, "mouse"_sv, "move"_sv,
    "movie"_sv, "much"_sv, "muffin"_sv, "mule"_sv, "multiply"_sv, "muscle"_sv, "museum"_sv, "mushroom"_sv, "music"_sv,
    "must"_sv, "mutual"_sv, "myself"_sv, "mystery"_sv, "myth"_sv, "naive"_sv, "name"_sv, "napkin"_sv, "narrow"_sv,
    "nasty"_sv, "nation"_sv, "nature"_sv, "near"_sv, "neck"_sv, "need"_sv, "negative"_sv, "neglect"_sv, "neither"_sv,
    "nephew"_sv, "nerve"_sv, "nest"_sv, "net"_sv, "network"_sv, "neutral"_sv, "never"_sv, "news"_sv, "next"_sv,
    "nice"_sv, "night"_sv, "noble"_sv, "noise"_sv, "nominee"_sv, "noodle"_sv, "normal"_sv, "north"_sv, "nose"_sv,
    "notable"_sv, "note"_sv, "nothing"_sv, "notice"_sv, "novel"_sv, "now"_sv, "nuclear"_sv, "number"_sv, "nurse"_sv,
    "nut"_sv, "oak"_sv, "obey"_sv, "object"_sv, "oblige"_sv, "obscure"_sv, "observe"_sv, "obtain"_sv, "obvious"_sv,
    "occur"_sv, "ocean"_sv, "october"_sv, "odor"_sv, "off"_sv, "offer"_sv, "office"_sv, "often"_sv, "oil"_sv,
    "okay"_sv, "old"_sv, "olive"_sv, "olympic"_sv, "omit"_sv, "once"_sv, "one"_sv, "onion"_sv, "online"_sv, "only"_sv,
    "open"_sv, "opera"_sv, "opinion"_sv, "oppose"_sv, "option"_sv, "orange"_sv, "orbit"_sv, "orchard"_sv, "order"_sv,
    "ordinary"_sv, "organ"_sv, "orient"_sv, "original"_sv, "orphan"_sv, "ostrich"_sv, "other"_sv, "outdoor"_sv,
    "outer"_sv, "output"_sv, "outside"_sv, "oval"_sv, "oven"_sv, "over"_sv, "own"_sv, "owner"_sv, "oxygen"_sv,
    "oyster"_sv, "ozone"_sv, "pact"_sv, "paddle"_sv, "page"_sv, "pair"_sv, "palace"_sv, "palm"_sv, "panda"_sv,
    "panel"_sv, "panic"_sv, "panther"_sv, "paper"_sv, "parade"_sv, "parent"_sv, "park"_sv, "parrot"_sv, "party"_sv,
    "pass"_sv, "patch"_sv, "path"_sv, "patient"_sv, "patrol"_sv, "pattern"_sv, "pause"_sv, "pave"_sv, "payment"_sv,
    "peace"_sv, "peanut"_sv, "pear"_sv, "peasant"_sv, "pelican"_sv, "pen"_sv, "penalty"_sv, "pencil"_sv, "people"_sv,
    "pepper"_sv, "perfect"_sv, "permit"_sv, "person"_sv, "pet"_sv, "phone"_sv, "photo"_sv, "phrase"_sv, "physical"_sv,
    "piano"_sv, "picnic"_sv, "picture"_sv, "piece"_sv, "pig"_sv, "pigeon"_sv, "pill"_sv, "pilot"_sv, "pink"_sv,
    "pioneer"_sv, "pipe"_sv, "pistol"_sv, "pitch"_sv, "pizza"_sv, "place"_sv, "planet"_sv, "plastic"_sv, "plate"_sv,
    "play"_sv, "please"_sv, "pledge"_sv, "pluck"_sv, "plug"_sv, "plunge"_sv, "poem"_sv, "poet"_sv, "point"_sv,
    "polar"_sv, "pole"_sv, "police"_sv, "pond"_sv, "pony"_sv, "pool"_sv, "popular"_sv, "portion"_sv, "position"_sv,
    "possible"_sv, "post"_sv, "potato"_sv, "pottery"_sv, "poverty"_sv, "powder"_sv, "power"_sv, "practice"_sv,
    "praise"_sv, "predict"_sv, "prefer"_sv, "prepare"_sv, "present"_sv, "pretty"_sv, "prevent"_sv, "price"_sv,
    "pride"_sv, "primary"_sv, "print"_sv, "priority"_sv, "prison"_sv, "private"_sv, "prize"_sv, "problem"_sv,
    "process"_sv, "produce"_sv, "profit"_sv, "program"_sv, "project"_sv, "promote"_sv, "proof"_sv, "property"_sv,
    "prosper"_sv, "protect"_sv, "proud"_sv, "provide"_sv, "public"_sv, "pudding"_sv, "pull"_sv, "pulp"_sv, "pulse"_sv,
    "pumpkin"_sv, "punch"_sv, "pupil"_sv, "puppy"_sv, "purchase"_sv, "purity"_sv, "purpose"_sv, "purse"_sv, "push"_sv,
    "put"_sv, "puzzle"_sv, "pyramid"_sv, "quality"_sv, "quantum"_sv, "quarter"_sv, "question"_sv, "quick"_sv,
    "quit"_sv, "quiz"_sv, "quote"_sv, "rabbit"_sv, "raccoon"_sv, "race"_sv, "rack"_sv, "radar"_sv, "radio"_sv,
    "rail"_sv, "rain"_sv, "raise"_sv, "rally"_sv, "ramp"_sv, "ranch"_sv, "random"_sv, "range"_sv, "rapid"_sv,
    "rare"_sv, "rate"_sv, "rather"_sv, "raven"_sv, "raw"_sv, "razor"_sv, "ready"_sv, "real"_sv, "reason"_sv,
    "rebel"_sv, "rebuild"_sv, "recall"_sv, "receive"_sv, "recipe"_sv, "record"_sv, "recycle"_sv, "reduce"_sv,
    "reflect"_sv, "reform"_sv, "refuse"_sv, "region"_sv, "regret"_sv, "regular"_sv, "reject"_sv, "relax"_sv,
    "release"_sv, "relief"_sv, "rely"_sv, "remain"_sv, "remember"_sv, "remind"_sv, "remove"_sv, "render"_sv,
    "renew"_sv, "rent"_sv, "reopen"_sv, "repair"_sv, "repeat"_sv, "replace"_sv, "report"_sv, "require"_sv, "rescue"_sv,
    "resemble"_sv, "resist"_sv, "resource"_sv, "response"_sv, "result"_sv, "retire"_sv, "retreat"_sv, "return"_sv,
    "reunion"_sv, "reveal"_sv, "review"_sv, "reward"_sv, "rhythm"_sv, "rib"_sv, "ribbon"_sv, "rice"_sv, "rich"_sv,
    "ride"_sv, "ridge"_sv, "rifle"_sv, "right"_sv, "rigid"_sv, "ring"_sv, "riot"_sv, "ripple"_sv, "risk"_sv,
    "ritual"_sv, "rival"_sv, "river"_sv, "road"_sv, "roast"_sv, "robot"_sv, "robust"_sv, "rocket"_sv, "romance"_sv,
    "roof"_sv, "rookie"_sv, "room"_sv, "rose"_sv, "rotate"_sv, "rough"_sv, "round"_sv, "route"_sv, "royal"_sv,
    "rubber"_sv, "rude"_sv, "rug"_sv, "rule"_sv, "run"_sv, "runway"_sv, "rural"_sv, "sad"_sv, "saddle"_sv,
    "sadness"_sv, "safe"_sv, "sail"_sv, "salad"_sv, "salmon"_sv, "salon"_sv, "salt"_sv, "salute"_sv, "same"_sv,
    "sample"_sv, "sand"_sv, "satisfy"_sv, "satoshi"_sv, "sauce"_sv, "sausage"_sv, "save"_sv, "say"_sv, "scale"_sv,
    "scan"_sv, "scare"_sv, "scatter"_sv, "scene"_sv, "scheme"_sv, "school"_sv, "science"_sv, "scissors"_sv,
    "scorpion"_sv, "scout"_sv, "scrap"_sv, "screen"_sv, "script"_sv, "scrub"_sv, "sea"_sv, "search"_sv, "season"_sv,
    "seat"_sv, "second"_sv, "secret"_sv, "section"_sv, "security"_sv, "seed"_sv, "seek"_sv, "segment"_sv, "select"_sv,
    "sell"_sv, "seminar"_sv, "senior"_sv, "sense"_sv, "sentence"_sv, "series"_sv, "service"_sv, "session"_sv,
    "settle"_sv, "setup"_sv, "seven"_sv, "shadow"_sv, "shaft"_sv, "shallow"_sv, "share"_sv, "shed"_sv, "shell"_sv,
    "sheriff"_sv, "shield"_sv, "shift"_sv, "shine"_sv, "ship"_sv, "shiver"_sv, "shock"_sv, "shoe"_sv, "shoot"_sv,
    "shop"_sv, "short"_sv, "shoulder"_sv, "shove"_sv, "shrimp"_sv, "shrug"_sv, "shuffle"_sv, "shy"_sv, "sibling"_sv,
    "sick"_sv, "side"_sv, "siege"_sv, "sight"_sv, "sign"_sv, "silent"_sv, "silk"_sv, "silly"_sv, "silver"_sv,
    "similar"_sv, "simple"_sv, "since"_sv, "sing"_sv, "siren"_sv, "sister"_sv, "situate"_sv, "six"_sv, "size"_sv,
    "skate"_sv, "sketch"_sv, "ski"_sv, "skill"_sv, "skin"_sv, "skirt"_sv, "skull"_sv, "slab"_sv, "slam"_sv, "sleep"_sv,
    "slender"_sv, "slice"_sv, "slide"_sv, "slight"_sv, "slim"_sv, "slogan"_sv, "slot"_sv, "slow"_sv, "slush"_sv,
    "small"_sv, "smart"_sv, "smile"_sv, "smoke"_sv, "smooth"_sv, "snack"_sv, "snake"_sv, "snap"_sv, "sniff"_sv,
    "snow"_sv, "soap"_sv, "soccer"_sv, "social"_sv, "sock"_sv, "soda"_sv, "soft"_sv, "solar"_sv, "soldier"_sv,
    "solid"_sv, "solution"_sv, "solve"_sv, "someone"_sv, "song"_sv, "soon"_sv, "sorry"_sv, "sort"_sv, "soul"_sv,
    "sound"_sv, "soup"_sv, "source"_sv, "south"_sv, "space"_sv, "spare"_sv, "spatial"_sv, "spawn"_sv, "speak"_sv,
    "special"_sv, "speed"_sv, "spell"_sv, "spend"_sv, "sphere"_sv, "spice"_sv, "spider"_sv, "spike"_sv, "spin"_sv,
    "spirit"_sv, "split"_sv, "spoil"_sv, "sponsor"_sv, "spoon"_sv, "sport"_sv, "spot"_sv, "spray"_sv, "spread"_sv,
    "spring"_sv, "spy"_sv, "square"_sv, "squeeze"_sv, "squirrel"_sv, "stable"_sv, "stadium"_sv, "staff"_sv, "stage"_sv,
    "stairs"_sv, "stamp"_sv, "stand"_sv, "start"_sv, "state"_sv, "stay"_sv, "steak"_sv, "steel"_sv, "stem"_sv,
    "step"_sv, "stereo"_sv, "stick"_sv, "still"_sv, "sting"_sv, "stock"_sv, "stomach"_sv, "stone"_sv, "stool"_sv,
    "story"_sv, "stove"_sv, "strategy"_sv, "street"_sv, "strike"_sv, "strong"_sv, "struggle"_sv, "student"_sv,
    "stuff"_sv, "stumble"_sv, "style"_sv, "subject"_sv, "submit"_sv, "subway"_sv, "success"_sv, "such"_sv, "sudden"_sv,
    "suffer"_sv, "sugar"_sv, "suggest"_sv, "suit"_sv, "summer"_sv, "sun"_sv, "sunny"_sv, "sunset"_sv, "super"_sv,
    "supply"_sv, "supreme"_sv, "sure"_sv, "surface"_sv, "surge"_sv, "surprise"_sv, "surround"_sv, "survey"_sv,
    "suspect"_sv, "sustain"_sv, "swallow"_sv, "swamp"_sv, "swap"_sv, "swarm"_sv, "swear"_sv, "sweet"_sv, "swift"_sv,
    "swim"_sv, "swing"_sv, "switch"_sv, "sword"_sv, "symbol"_sv, "symptom"_sv, "syrup"_sv, "system"_sv, "table"_sv,
    "tackle"_sv, "tag"_sv, "tail"_sv, "talent"_sv, "talk"_sv, "tank"_sv, "tape"_sv, "target"_sv, "task"_sv, "taste"_sv,
    "tattoo"_sv, "taxi"_sv, "teach"_sv, "team"_sv, "tell"_sv, "ten"_sv, "tenant"_sv, "tennis"_sv, "tent"_sv, "term"_sv,
    "test"_sv, "text"_sv, "thank"_sv, "that"_sv, "theme"_sv, "then"_sv, "theory"_sv, "there"_sv, "they"_sv, "thing"_sv,
    "this"_sv, "thought"_sv, "three"_sv, "thrive"_sv, "throw"_sv, "thumb"_sv, "thunder"_sv, "ticket"_sv, "tide"_sv,
    "tiger"_sv, "tilt"_sv, "timber"_sv, "time"_sv, "tiny"_sv, "tip"_sv, "tired"_sv, "tissue"_sv, "title"_sv,
    "toast"_sv, "tobacco"_sv, "today"_sv, "toddler"_sv, "toe"_sv, "together"_sv, "toilet"_sv, "token"_sv, "tomato"_sv,
    "tomorrow"_sv, "tone"_sv, "tongue"_sv, "tonight"_sv, "tool"_sv, "tooth"_sv, "top"_sv, "topic"_sv, "topple"_sv,
    "torch"_sv, "tornado"_sv, "tortoise"_sv, "toss"_sv, "total"_sv, "tourist"_sv, "toward"_sv, "tower"_sv, "town"_sv,
    "toy"_sv, "track"_sv, "trade"_sv, "traffic"_sv, "tragic"_sv, "train"_sv, "transfer"_sv, "trap"_sv, "trash"_sv,
    "travel"_sv, "tray"_sv, "treat"_sv, "tree"_sv, "trend"_sv, "trial"_sv, "tribe"_sv, "trick"_sv, "trigger"_sv,
    "trim"_sv, "trip"_sv, "trophy"_sv, "trouble"_sv, "truck"_sv, "true"_sv, "truly"_sv, "trumpet"_sv, "trust"_sv,
    "truth"_sv, "try"_sv, "tube"_sv, "tuition"_sv, "tumble"_sv, "tuna"_sv, "tunnel"_sv, "turkey"_sv, "turn"_sv,
    "turtle"_sv, "twelve"_sv, "twenty"_sv, "twice"_sv, "twin"_sv, "twist"_sv, "two"_sv, "type"_sv, "typical"_sv,
    "ugly"_sv, "umbrella"_sv, "unable"_sv, "unaware"_sv, "uncle"_sv, "uncover"_sv, "under"_sv, "undo"_sv, "unfair"_sv,
    "unfold"_sv, "unhappy"_sv, "uniform"_sv, "unique"_sv, "unit"_sv, "universe"_sv, "unknown"_sv, "unlock"_sv,
    "until"_sv, "unusual"_sv, "unveil"_sv, "update"_sv, "upgrade"_sv, "uphold"_sv, "upon"_sv, "upper"_sv, "upset"_sv,
    "urban"_sv, "urge"_sv, "usage"_sv, "use"_sv, "used"_sv, "useful"_sv, "useless"_sv, "usual"_sv, "utility"_sv,
    "vacant"_sv, "vacuum"_sv, "vague"_sv, "valid"_sv, "valley"_sv, "valve"_sv, "van"_sv, "vanish"_sv, "vapor"_sv,
    "various"_sv, "vast"_sv, "vault"_sv, "vehicle"_sv, "velvet"_sv, "vendor"_sv, "venture"_sv, "venue"_sv, "verb"_sv,
    "verify"_sv, "version"_sv, "very"_sv, "vessel"_sv, "veteran"_sv, "viable"_sv, "vibrant"_sv, "vicious"_sv,
    "victory"_sv, "video"_sv, "view"_sv, "village"_sv, "vintage"_sv, "violin"_sv, "virtual"_sv, "virus"_sv, "visa"_sv,
    "visit"_sv, "visual"_sv, "vital"_sv, "vivid"_sv, "vocal"_sv, "voice"_sv, "void"_sv, "volcano"_sv, "volume"_sv,
    "vote"_sv, "voyage"_sv, "wage"_sv, "wagon"_sv, "wait"_sv, "walk"_sv, "wall"_sv, "walnut"_sv, "want"_sv,
    "warfare"_sv, "warm"_sv, "warrior"_sv, "wash"_sv, "wasp"_sv, "waste"_sv, "water"_sv, "wave"_sv, "way"_sv,
    "wealth"_sv, "weapon"_sv, "wear"_sv, "weasel"_sv, "weather"_sv, "web"_sv, "wedding"_sv, "weekend"_sv, "weird"_sv,
    "welcome"_sv, "west"_sv, "wet"_sv, "whale"_sv, "what"_sv, "wheat"_sv, "wheel"_sv, "when"_sv, "where"_sv, "whip"_sv,
    "whisper"_sv, "wide"_sv, "width"_sv, "wife"_sv, "wild"_sv, "will"_sv, "win"_sv, "window"_sv, "wine"_sv, "wing"_sv,
    "wink"_sv, "winner"_sv, "winter"_sv, "wire"_sv, "wisdom"_sv, "wise"_sv, "wish"_sv, "witness"_sv, "wolf"_sv,
    "woman"_sv, "wonder"_sv, "wood"_sv, "wool"_sv, "word"_sv, "work"_sv, "world"_sv, "worry"_sv, "worth"_sv, "wrap"_sv,
    "wreck"_sv, "wrestle"_sv, "wrist"_sv, "write"_sv, "wrong"_sv, "yard"_sv, "year"_sv, "yellow"_sv, "you"_sv,
    "young"_sv, "youth"_sv, "zebra"_sv, "zero"_sv, "zone"_sv, "zoo"_sv,
    };

    return ids;
}

wordlist_t& ::bip0039::wordlistStaticShuffle()
{
    static array<cstrview, 2048> ids
    {
    "early"_sv, "lift"_sv, "sail"_sv, "parent"_sv, "cancel"_sv, "debate"_sv, "small"_sv, "usual"_sv, "stock"_sv,
    "fiscal"_sv, "soldier"_sv, "heart"_sv, "surge"_sv, "vocal"_sv, "opera"_sv, "swarm"_sv, "list"_sv, "payment"_sv,
    "inside"_sv, "retire"_sv, "bitter"_sv, "popular"_sv, "ask"_sv, "double"_sv, "man"_sv, "pyramid"_sv, "immune"_sv,
    "diet"_sv, "duck"_sv, "alert"_sv, "jacket"_sv, "menu"_sv, "tool"_sv, "knee"_sv, "cluster"_sv, "crack"_sv,
    "point"_sv, "vintage"_sv, "rate"_sv, "glove"_sv, "physical"_sv, "expire"_sv, "case"_sv, "salt"_sv, "album"_sv,
    "million"_sv, "same"_sv, "cash"_sv, "mercy"_sv, "ceiling"_sv, "inch"_sv, "element"_sv, "absurd"_sv, "distance"_sv,
    "stay"_sv, "believe"_sv, "glide"_sv, "enemy"_sv, "weekend"_sv, "frequent"_sv, "clerk"_sv, "guard"_sv,
    "hospital"_sv, "chase"_sv, "suggest"_sv, "admit"_sv, "oyster"_sv, "search"_sv, "business"_sv, "ill"_sv,
    "matrix"_sv, "flower"_sv, "size"_sv, "argue"_sv, "chief"_sv, "ticket"_sv, "intact"_sv, "identify"_sv, "addict"_sv,
    "lock"_sv, "birth"_sv, "upper"_sv, "interest"_sv, "virus"_sv, "flip"_sv, "reveal"_sv, "rotate"_sv, "city"_sv,
    "crash"_sv, "congress"_sv, "crunch"_sv, "assault"_sv, "vital"_sv, "sibling"_sv, "melody"_sv, "prize"_sv, "gun"_sv,
    "fee"_sv, "eternal"_sv, "circle"_sv, "allow"_sv, "amazing"_sv, "smoke"_sv, "entire"_sv, "wrist"_sv, "state"_sv,
    "category"_sv, "afford"_sv, "mention"_sv, "close"_sv, "chalk"_sv, "walk"_sv, "indicate"_sv, "blouse"_sv,
    "cloud"_sv, "federal"_sv, "gallery"_sv, "tennis"_sv, "powder"_sv, "dignity"_sv, "pole"_sv, "aim"_sv, "evil"_sv,
    "replace"_sv, "auction"_sv, "struggle"_sv, "lava"_sv, "example"_sv, "toss"_sv, "balance"_sv, "pass"_sv,
    "simple"_sv, "peanut"_sv, "height"_sv, "sister"_sv, "snack"_sv, "unit"_sv, "glare"_sv, "near"_sv, "whisper"_sv,
    "taste"_sv, "turtle"_sv, "glass"_sv, "season"_sv, "leopard"_sv, "tuition"_sv, "cage"_sv, "rain"_sv, "today"_sv,
    "panda"_sv, "loan"_sv, "sorry"_sv, "pitch"_sv, "brand"_sv, "unfair"_sv, "mountain"_sv, "cheese"_sv, "oblige"_sv,
    "strong"_sv, "victory"_sv, "like"_sv, "labor"_sv, "devote"_sv, "web"_sv, "dawn"_sv, "erosion"_sv, "maximum"_sv,
    "into"_sv, "mistake"_sv, "ginger"_sv, "indoor"_sv, "essence"_sv, "anxiety"_sv, "prefer"_sv, "own"_sv, "quantum"_sv,
    "rose"_sv, "service"_sv, "weird"_sv, "hazard"_sv, "ladder"_sv, "book"_sv, "dry"_sv, "innocent"_sv, "globe"_sv,
    "scorpion"_sv, "remain"_sv, "girl"_sv, "portion"_sv, "food"_sv, "eagle"_sv, "lawn"_sv, "material"_sv, "nerve"_sv,
    "make"_sv, "loyal"_sv, "current"_sv, "column"_sv, "skin"_sv, "slab"_sv, "pink"_sv, "disease"_sv, "sunset"_sv,
    "choice"_sv, "acoustic"_sv, "fitness"_sv, "neither"_sv, "analyst"_sv, "doctor"_sv, "unusual"_sv, "crouch"_sv,
    "mixture"_sv, "negative"_sv, "unlock"_sv, "dilemma"_sv, "forget"_sv, "frog"_sv, "smooth"_sv, "frozen"_sv,
    "project"_sv, "slice"_sv, "seat"_sv, "screen"_sv, "box"_sv, "arm"_sv, "sketch"_sv, "raw"_sv, "cement"_sv,
    "bike"_sv, "eye"_sv, "add"_sv, "risk"_sv, "program"_sv, "good"_sv, "nation"_sv, "profit"_sv, "drive"_sv, "vote"_sv,
    "rebel"_sv, "frown"_sv, "bargain"_sv, "owner"_sv, "monitor"_sv, "core"_sv, "window"_sv, "retreat"_sv, "mom"_sv,
    "ostrich"_sv, "expose"_sv, "few"_sv, "pig"_sv, "comic"_sv, "verb"_sv, "pool"_sv, "kit"_sv, "zebra"_sv, "urban"_sv,
    "pluck"_sv, "arrow"_sv, "peace"_sv, "normal"_sv, "leg"_sv, "begin"_sv, "artist"_sv, "bronze"_sv, "symbol"_sv,
    "club"_sv, "anchor"_sv, "piano"_sv, "shock"_sv, "zone"_sv, "only"_sv, "aspect"_sv, "satoshi"_sv, "duty"_sv,
    "shove"_sv, "coach"_sv, "orient"_sv, "law"_sv, "trouble"_sv, "fatal"_sv, "turn"_sv, "ecology"_sv, "language"_sv,
    "develop"_sv, "afraid"_sv, "chronic"_sv, "almost"_sv, "silly"_sv, "ring"_sv, "harbor"_sv, "rude"_sv, "aunt"_sv,
    "room"_sv, "miracle"_sv, "toddler"_sv, "file"_sv, "dice"_sv, "clump"_sv, "kidney"_sv, "father"_sv, "half"_sv,
    "cave"_sv, "month"_sv, "shuffle"_sv, "uncover"_sv, "expand"_sv, "boat"_sv, "depart"_sv, "abandon"_sv, "garage"_sv,
    "neck"_sv, "claw"_sv, "open"_sv, "lunar"_sv, "belt"_sv, "media"_sv, "museum"_sv, "impulse"_sv, "lottery"_sv,
    "puzzle"_sv, "prevent"_sv, "round"_sv, "tower"_sv, "office"_sv, "tourist"_sv, "rely"_sv, "object"_sv, "large"_sv,
    "scan"_sv, "impact"_sv, "unhappy"_sv, "place"_sv, "skill"_sv, "silk"_sv, "wagon"_sv, "badge"_sv, "void"_sv,
    "witness"_sv, "recall"_sv, "jump"_sv, "gain"_sv, "brass"_sv, "stand"_sv, "abuse"_sv, "habit"_sv, "mesh"_sv,
    "earth"_sv, "photo"_sv, "spell"_sv, "leader"_sv, "lucky"_sv, "depth"_sv, "exclude"_sv, "knock"_sv, "critic"_sv,
    "harsh"_sv, "setup"_sv, "gather"_sv, "convince"_sv, "since"_sv, "armed"_sv, "travel"_sv, "umbrella"_sv, "deny"_sv,
    "include"_sv, "ivory"_sv, "riot"_sv, "unveil"_sv, "purse"_sv, "between"_sv, "smile"_sv, "tomorrow"_sv, "west"_sv,
    "shield"_sv, "fever"_sv, "lamp"_sv, "domain"_sv, "awake"_sv, "galaxy"_sv, "direct"_sv, "catch"_sv, "border"_sv,
    "squirrel"_sv, "battle"_sv, "hover"_sv, "toilet"_sv, "deal"_sv, "long"_sv, "word"_sv, "impose"_sv, "mystery"_sv,
    "first"_sv, "bulk"_sv, "rich"_sv, "quarter"_sv, "hard"_sv, "dove"_sv, "journey"_sv, "recycle"_sv, "neglect"_sv,
    "limit"_sv, "marine"_sv, "around"_sv, "legal"_sv, "vendor"_sv, "eight"_sv, "kitchen"_sv, "traffic"_sv, "flight"_sv,
    "enjoy"_sv, "pepper"_sv, "love"_sv, "dentist"_sv, "decorate"_sv, "jaguar"_sv, "bleak"_sv, "tape"_sv, "top"_sv,
    "bring"_sv, "recipe"_sv, "leisure"_sv, "spirit"_sv, "sun"_sv, "lesson"_sv, "bag"_sv, "voyage"_sv, "public"_sv,
    "butter"_sv, "remove"_sv, "select"_sv, "gas"_sv, "insane"_sv, "camp"_sv, "canal"_sv, "call"_sv, "hobby"_sv,
    "degree"_sv, "depend"_sv, "practice"_sv, "cigar"_sv, "float"_sv, "arch"_sv, "castle"_sv, "myself"_sv, "tilt"_sv,
    "clap"_sv, "blue"_sv, "then"_sv, "solution"_sv, "timber"_sv, "fall"_sv, "bone"_sv, "sad"_sv, "tuna"_sv, "north"_sv,
    "water"_sv, "clinic"_sv, "basic"_sv, "phrase"_sv, "happy"_sv, "subway"_sv, "security"_sv, "accident"_sv,
    "visit"_sv, "usage"_sv, "miss"_sv, "catalog"_sv, "goose"_sv, "above"_sv, "rhythm"_sv, "injury"_sv, "fork"_sv,
    "release"_sv, "vibrant"_sv, "away"_sv, "boy"_sv, "secret"_sv, "report"_sv, "friend"_sv, "settle"_sv, "fox"_sv,
    "ancient"_sv, "awkward"_sv, "swim"_sv, "foil"_sv, "wife"_sv, "bridge"_sv, "pear"_sv, "road"_sv, "black"_sv,
    "body"_sv, "humor"_sv, "surround"_sv, "tone"_sv, "cattle"_sv, "spice"_sv, "empower"_sv, "civil"_sv, "push"_sv,
    "hundred"_sv, "spider"_sv, "action"_sv, "visual"_sv, "finish"_sv, "valid"_sv, "very"_sv, "champion"_sv, "aisle"_sv,
    "universe"_sv, "urge"_sv, "cover"_sv, "emerge"_sv, "cricket"_sv, "wish"_sv, "hip"_sv, "glance"_sv, "avoid"_sv,
    "basket"_sv, "gospel"_sv, "primary"_sv, "income"_sv, "wrong"_sv, "inflict"_sv, "airport"_sv, "desert"_sv,
    "control"_sv, "shiver"_sv, "sock"_sv, "orphan"_sv, "artwork"_sv, "entry"_sv, "fruit"_sv, "clock"_sv, "result"_sv,
    "tonight"_sv, "trial"_sv, "machine"_sv, "hurdle"_sv, "vehicle"_sv, "copper"_sv, "forward"_sv, "nice"_sv,
    "rapid"_sv, "animal"_sv, "pistol"_sv, "seminar"_sv, "cabin"_sv, "obey"_sv, "february"_sv, "original"_sv, "cart"_sv,
    "fossil"_sv, "poverty"_sv, "volume"_sv, "more"_sv, "matter"_sv, "grab"_sv, "minute"_sv, "reduce"_sv, "couch"_sv,
    "heavy"_sv, "later"_sv, "gossip"_sv, "answer"_sv, "clean"_sv, "route"_sv, "idle"_sv, "credit"_sv, "access"_sv,
    "invite"_sv, "flash"_sv, "hold"_sv, "defy"_sv, "jungle"_sv, "rally"_sv, "ice"_sv, "icon"_sv, "luggage"_sv,
    "situate"_sv, "cup"_sv, "green"_sv, "brother"_sv, "unable"_sv, "layer"_sv, "twenty"_sv, "still"_sv, "nominee"_sv,
    "six"_sv, "never"_sv, "unique"_sv, "pizza"_sv, "veteran"_sv, "another"_sv, "genuine"_sv, "oil"_sv, "plastic"_sv,
    "twist"_sv, "major"_sv, "olive"_sv, "grain"_sv, "child"_sv, "burst"_sv, "across"_sv, "lounge"_sv, "kite"_sv,
    "suit"_sv, "bubble"_sv, "turkey"_sv, "inject"_sv, "economy"_sv, "again"_sv, "stomach"_sv, "insect"_sv, "arctic"_sv,
    "better"_sv, "speed"_sv, "merit"_sv, "super"_sv, "offer"_sv, "combine"_sv, "gesture"_sv, "brown"_sv, "similar"_sv,
    "calm"_sv, "reopen"_sv, "either"_sv, "coin"_sv, "decline"_sv, "rescue"_sv, "priority"_sv, "bid"_sv, "twice"_sv,
    "horse"_sv, "soup"_sv, "stairs"_sv, "fiction"_sv, "mushroom"_sv, "guitar"_sv, "paper"_sv, "cousin"_sv, "beach"_sv,
    "vessel"_sv, "middle"_sv, "canyon"_sv, "short"_sv, "angry"_sv, "return"_sv, "worth"_sv, "stick"_sv, "scheme"_sv,
    "candy"_sv, "ozone"_sv, "rigid"_sv, "embark"_sv, "crush"_sv, "toe"_sv, "put"_sv, "trip"_sv, "network"_sv,
    "kitten"_sv, "canvas"_sv, "reflect"_sv, "brisk"_sv, "false"_sv, "trap"_sv, "group"_sv, "clarify"_sv, "soul"_sv,
    "ability"_sv, "sense"_sv, "enact"_sv, "right"_sv, "moon"_sv, "grow"_sv, "tenant"_sv, "stool"_sv, "hen"_sv,
    "paddle"_sv, "cotton"_sv, "flame"_sv, "magnet"_sv, "diagram"_sv, "supreme"_sv, "scrap"_sv, "property"_sv,
    "become"_sv, "fault"_sv, "two"_sv, "erase"_sv, "picture"_sv, "truth"_sv, "apple"_sv, "explain"_sv, "rent"_sv,
    "jeans"_sv, "inner"_sv, "draft"_sv, "hurry"_sv, "carpet"_sv, "tree"_sv, "senior"_sv, "pioneer"_sv, "cliff"_sv,
    "bachelor"_sv, "switch"_sv, "crumble"_sv, "mandate"_sv, "plate"_sv, "grunt"_sv, "text"_sv, "dream"_sv, "loud"_sv,
    "radar"_sv, "stage"_sv, "aerobic"_sv, "spawn"_sv, "scale"_sv, "bright"_sv, "capital"_sv, "method"_sv, "blood"_sv,
    "time"_sv, "blind"_sv, "glad"_sv, "solar"_sv, "chuckle"_sv, "dragon"_sv, "buzz"_sv, "village"_sv, "record"_sv,
    "build"_sv, "pond"_sv, "brush"_sv, "manage"_sv, "drip"_sv, "drill"_sv, "scout"_sv, "tackle"_sv, "swamp"_sv,
    "theory"_sv, "garlic"_sv, "will"_sv, "master"_sv, "saddle"_sv, "acid"_sv, "wine"_sv, "safe"_sv, "pretty"_sv,
    "jealous"_sv, "symptom"_sv, "slush"_sv, "bonus"_sv, "section"_sv, "vast"_sv, "trigger"_sv, "decrease"_sv,
    "silver"_sv, "sword"_sv, "arrest"_sv, "blossom"_sv, "spring"_sv, "execute"_sv, "talk"_sv, "under"_sv, "warrior"_sv,
    "roast"_sv, "trust"_sv, "describe"_sv, "moment"_sv, "maze"_sv, "carry"_sv, "dutch"_sv, "warm"_sv, "merge"_sv,
    "increase"_sv, "way"_sv, "beauty"_sv, "avocado"_sv, "total"_sv, "hidden"_sv, "grid"_sv, "assist"_sv, "diary"_sv,
    "poem"_sv, "connect"_sv, "spatial"_sv, "mobile"_sv, "mimic"_sv, "hollow"_sv, "pill"_sv, "ketchup"_sv, "strike"_sv,
    "torch"_sv, "upon"_sv, "energy"_sv, "social"_sv, "robust"_sv, "welcome"_sv, "ugly"_sv, "message"_sv, "head"_sv,
    "manual"_sv, "budget"_sv, "east"_sv, "broom"_sv, "slender"_sv, "clip"_sv, "faith"_sv, "proof"_sv, "must"_sv,
    "index"_sv, "seek"_sv, "cruise"_sv, "kingdom"_sv, "mean"_sv, "wise"_sv, "dash"_sv, "else"_sv, "eyebrow"_sv,
    "fresh"_sv, "correct"_sv, "task"_sv, "prosper"_sv, "dog"_sv, "useful"_sv, "virtual"_sv, "coral"_sv, "warfare"_sv,
    "write"_sv, "key"_sv, "giggle"_sv, "fish"_sv, "blanket"_sv, "stamp"_sv, "bullet"_sv, "document"_sv, "wreck"_sv,
    "squeeze"_sv, "betray"_sv, "series"_sv, "design"_sv, "position"_sv, "song"_sv, "measure"_sv, "sight"_sv,
    "confirm"_sv, "wolf"_sv, "cream"_sv, "voice"_sv, "spike"_sv, "elephant"_sv, "jar"_sv, "please"_sv, "lazy"_sv,
    "stuff"_sv, "milk"_sv, "rocket"_sv, "ride"_sv, "cherry"_sv, "fatigue"_sv, "drastic"_sv, "tag"_sv, "exact"_sv,
    "world"_sv, "advice"_sv, "blame"_sv, "apart"_sv, "ribbon"_sv, "august"_sv, "real"_sv, "strategy"_sv, "amused"_sv,
    "chapter"_sv, "embrace"_sv, "tip"_sv, "library"_sv, "mosquito"_sv, "receive"_sv, "donate"_sv, "garment"_sv,
    "baby"_sv, "antenna"_sv, "fetch"_sv, "garbage"_sv, "monster"_sv, "bless"_sv, "quiz"_sv, "fluid"_sv, "power"_sv,
    "scrub"_sv, "run"_sv, "evoke"_sv, "egg"_sv, "swing"_sv, "magic"_sv, "maple"_sv, "fun"_sv, "gentle"_sv, "danger"_sv,
    "easy"_sv, "coyote"_sv, "slide"_sv, "stereo"_sv, "life"_sv, "tomato"_sv, "gaze"_sv, "bamboo"_sv, "end"_sv,
    "cry"_sv, "wire"_sv, "unfold"_sv, "alien"_sv, "vault"_sv, "acquire"_sv, "transfer"_sv, "glue"_sv, "scene"_sv,
    "anger"_sv, "resource"_sv, "thought"_sv, "stadium"_sv, "health"_sv, "violin"_sv, "keep"_sv, "option"_sv,
    "exhaust"_sv, "hat"_sv, "protect"_sv, "mouse"_sv, "sphere"_sv, "sudden"_sv, "visa"_sv, "ready"_sv, "scatter"_sv,
    "fog"_sv, "output"_sv, "vague"_sv, "seven"_sv, "weather"_sv, "spare"_sv, "grit"_sv, "era"_sv, "olympic"_sv,
    "link"_sv, "regular"_sv, "dismiss"_sv, "wink"_sv, "crime"_sv, "dinosaur"_sv, "woman"_sv, "salute"_sv,
    "purchase"_sv, "have"_sv, "subject"_sv, "autumn"_sv, "sign"_sv, "upgrade"_sv, "win"_sv, "check"_sv, "sleep"_sv,
    "imitate"_sv, "toy"_sv, "orange"_sv, "town"_sv, "play"_sv, "echo"_sv, "team"_sv, "valley"_sv, "illegal"_sv,
    "refuse"_sv, "flush"_sv, "tent"_sv, "debris"_sv, "shed"_sv, "asthma"_sv, "other"_sv, "potato"_sv, "sell"_sv,
    "client"_sv, "feel"_sv, "wall"_sv, "agree"_sv, "celery"_sv, "live"_sv, "door"_sv, "behind"_sv, "render"_sv,
    "surface"_sv, "tide"_sv, "game"_sv, "drink"_sv, "often"_sv, "cross"_sv, "memory"_sv, "luxury"_sv, "hybrid"_sv,
    "wool"_sv, "prison"_sv, "demand"_sv, "damp"_sv, "actor"_sv, "apology"_sv, "century"_sv, "planet"_sv, "laugh"_sv,
    "account"_sv, "online"_sv, "trade"_sv, "bracket"_sv, "wait"_sv, "rule"_sv, "brief"_sv, "people"_sv, "keen"_sv,
    "gasp"_sv, "census"_sv, "edge"_sv, "pact"_sv, "issue"_sv, "honey"_sv, "scissors"_sv, "dinner"_sv, "industry"_sv,
    "cushion"_sv, "tornado"_sv, "help"_sv, "exercise"_sv, "ship"_sv, "side"_sv, "famous"_sv, "already"_sv, "hour"_sv,
    "bench"_sv, "private"_sv, "onion"_sv, "sick"_sv, "update"_sv, "price"_sv, "pudding"_sv, "learn"_sv, "gym"_sv,
    "toast"_sv, "antique"_sv, "story"_sv, "board"_sv, "multiply"_sv, "cat"_sv, "always"_sv, "swallow"_sv, "zero"_sv,
    "move"_sv, "say"_sv, "hint"_sv, "fuel"_sv, "trumpet"_sv, "flee"_sv, "sentence"_sv, "flock"_sv, "fiber"_sv,
    "steak"_sv, "change"_sv, "charge"_sv, "infant"_sv, "reason"_sv, "disorder"_sv, "patient"_sv, "various"_sv,
    "stem"_sv, "much"_sv, "forest"_sv, "click"_sv, "pilot"_sv, "guess"_sv, "illness"_sv, "wisdom"_sv, "velvet"_sv,
    "jelly"_sv, "slot"_sv, "axis"_sv, "lizard"_sv, "day"_sv, "female"_sv, "pull"_sv, "left"_sv, "edit"_sv, "person"_sv,
    "south"_sv, "fantasy"_sv, "divert"_sv, "napkin"_sv, "reward"_sv, "decide"_sv, "hand"_sv, "okay"_sv, "mule"_sv,
    "when"_sv, "hammer"_sv, "laundry"_sv, "shrug"_sv, "input"_sv, "figure"_sv, "sound"_sv, "raccoon"_sv, "repeat"_sv,
    "taxi"_sv, "tissue"_sv, "royal"_sv, "nephew"_sv, "volcano"_sv, "destroy"_sv, "margin"_sv, "orbit"_sv, "inmate"_sv,
    "inhale"_sv, "toward"_sv, "now"_sv, "deer"_sv, "chunk"_sv, "boring"_sv, "wheat"_sv, "dumb"_sv, "sweet"_sv,
    "thumb"_sv, "pet"_sv, "hunt"_sv, "pulp"_sv, "hurt"_sv, "crowd"_sv, "soccer"_sv, "swear"_sv, "wash"_sv, "absorb"_sv,
    "curtain"_sv, "hedgehog"_sv, "math"_sv, "wedding"_sv, "dance"_sv, "rabbit"_sv, "slogan"_sv, "kiwi"_sv,
    "fragile"_sv, "meat"_sv, "yard"_sv, "fence"_sv, "brain"_sv, "blur"_sv, "test"_sv, "park"_sv, "palace"_sv,
    "hotel"_sv, "copy"_sv, "ritual"_sv, "problem"_sv, "endorse"_sv, "pulse"_sv, "random"_sv, "cruel"_sv, "arrange"_sv,
    "target"_sv, "crisp"_sv, "such"_sv, "certain"_sv, "digital"_sv, "permit"_sv, "fat"_sv, "shrimp"_sv, "frame"_sv,
    "shop"_sv, "tube"_sv, "motor"_sv, "slight"_sv, "craft"_sv, "tank"_sv, "video"_sv, "actress"_sv, "disagree"_sv,
    "act"_sv, "absent"_sv, "occur"_sv, "display"_sv, "high"_sv, "corn"_sv, "crop"_sv, "car"_sv, "genius"_sv, "loop"_sv,
    "trash"_sv, "daughter"_sv, "supply"_sv, "promote"_sv, "abstract"_sv, "guide"_sv, "require"_sv, "effort"_sv,
    "spend"_sv, "gravity"_sv, "drop"_sv, "artefact"_sv, "can"_sv, "borrow"_sv, "exile"_sv, "market"_sv, "spin"_sv,
    "final"_sv, "bird"_sv, "cargo"_sv, "mammal"_sv, "exit"_sv, "snake"_sv, "punch"_sv, "salon"_sv, "company"_sv,
    "fortune"_sv, "label"_sv, "worry"_sv, "excess"_sv, "biology"_sv, "range"_sv, "survey"_sv, "hope"_sv, "panel"_sv,
    "caution"_sv, "creek"_sv, "provide"_sv, "culture"_sv, "invest"_sv, "hub"_sv, "tray"_sv, "buffalo"_sv, "clutch"_sv,
    "foam"_sv, "typical"_sv, "second"_sv, "title"_sv, "gift"_sv, "page"_sv, "ridge"_sv, "cost"_sv, "bundle"_sv,
    "draw"_sv, "cram"_sv, "monkey"_sv, "weapon"_sv, "carbon"_sv, "lens"_sv, "able"_sv, "citizen"_sv, "siren"_sv,
    "discover"_sv, "skate"_sv, "mad"_sv, "square"_sv, "pave"_sv, "finger"_sv, "judge"_sv, "curve"_sv, "fire"_sv,
    "crucial"_sv, "plunge"_sv, "produce"_sv, "glimpse"_sv, "start"_sv, "beef"_sv, "marble"_sv, "faint"_sv, "floor"_sv,
    "chef"_sv, "panic"_sv, "oven"_sv, "want"_sv, "grass"_sv, "track"_sv, "scare"_sv, "home"_sv, "yellow"_sv,
    "satisfy"_sv, "spoon"_sv, "diesel"_sv, "snow"_sv, "zoo"_sv, "field"_sv, "school"_sv, "rebuild"_sv, "used"_sv,
    "summer"_sv, "stove"_sv, "deposit"_sv, "fine"_sv, "print"_sv, "save"_sv, "announce"_sv, "error"_sv, "deputy"_sv,
    "hello"_sv, "tattoo"_sv, "captain"_sv, "inform"_sv, "parrot"_sv, "enrich"_sv, "wing"_sv, "broken"_sv, "bomb"_sv,
    "accuse"_sv, "earn"_sv, "alter"_sv, "lion"_sv, "dolphin"_sv, "neutral"_sv, "farm"_sv, "coffee"_sv, "local"_sv,
    "join"_sv, "snap"_sv, "they"_sv, "smart"_sv, "ensure"_sv, "exchange"_sv, "find"_sv, "version"_sv, "work"_sv,
    "drift"_sv, "stable"_sv, "detail"_sv, "crane"_sv, "salmon"_sv, "novel"_sv, "nurse"_sv, "busy"_sv, "foot"_sv,
    "roof"_sv, "any"_sv, "model"_sv, "junk"_sv, "use"_sv, "relief"_sv, "pen"_sv, "blast"_sv, "episode"_sv, "mass"_sv,
    "crew"_sv, "once"_sv, "great"_sv, "shift"_sv, "rack"_sv, "topple"_sv, "tongue"_sv, "level"_sv, "lemon"_sv,
    "alcohol"_sv, "benefit"_sv, "quit"_sv, "logic"_sv, "fade"_sv, "differ"_sv, "athlete"_sv, "table"_sv, "parade"_sv,
    "where"_sv, "modify"_sv, "lumber"_sv, "liar"_sv, "obvious"_sv, "embody"_sv, "trim"_sv, "truly"_sv, "shoot"_sv,
    "funny"_sv, "flag"_sv, "brave"_sv, "glory"_sv, "lawsuit"_sv, "bread"_sv, "light"_sv, "buddy"_sv, "course"_sv,
    "shaft"_sv, "angle"_sv, "throw"_sv, "raise"_sv, "mirror"_sv, "raven"_sv, "enroll"_sv, "face"_sv, "regret"_sv,
    "present"_sv, "poet"_sv, "april"_sv, "attend"_sv, "ankle"_sv, "slow"_sv, "clever"_sv, "purity"_sv, "common"_sv,
    "police"_sv, "topic"_sv, "midnight"_sv, "lunch"_sv, "family"_sv, "vacuum"_sv, "mixed"_sv, "cable"_sv, "ahead"_sv,
    "odor"_sv, "engage"_sv, "divide"_sv, "theme"_sv, "teach"_sv, "purpose"_sv, "oval"_sv, "electric"_sv, "science"_sv,
    "limb"_sv, "soap"_sv, "ramp"_sv, "found"_sv, "spoil"_sv, "skull"_sv, "style"_sv, "predict"_sv, "audit"_sv,
    "oak"_sv, "runway"_sv, "fit"_sv, "that"_sv, "bar"_sv, "noble"_sv, "idea"_sv, "burden"_sv, "remind"_sv, "metal"_sv,
    "filter"_sv, "fringe"_sv, "camera"_sv, "thunder"_sv, "outside"_sv, "sunny"_sv, "lecture"_sv, "wet"_sv, "demise"_sv,
    "giant"_sv, "sample"_sv, "conduct"_sv, "syrup"_sv, "daring"_sv, "talent"_sv, "cradle"_sv, "quick"_sv, "enlist"_sv,
    "enhance"_sv, "thank"_sv, "enter"_sv, "banner"_sv, "misery"_sv, "kick"_sv, "ocean"_sv, "adapt"_sv, "year"_sv,
    "pride"_sv, "what"_sv, "alone"_sv, "blade"_sv, "gorilla"_sv, "kiss"_sv, "iron"_sv, "chimney"_sv, "hockey"_sv,
    "review"_sv, "repair"_sv, "capable"_sv, "pattern"_sv, "equal"_sv, "extra"_sv, "staff"_sv, "wave"_sv, "omit"_sv,
    "cabbage"_sv, "pottery"_sv, "system"_sv, "item"_sv, "bottom"_sv, "author"_sv, "collect"_sv, "initial"_sv,
    "inquiry"_sv, "easily"_sv, "panther"_sv, "train"_sv, "ghost"_sv, "trend"_sv, "delay"_sv, "suffer"_sv, "march"_sv,
    "student"_sv, "mask"_sv, "force"_sv, "feed"_sv, "sea"_sv, "grape"_sv, "legend"_sv, "script"_sv, "winner"_sv,
    "doll"_sv, "joy"_sv, "coconut"_sv, "name"_sv, "age"_sv, "walnut"_sv, "spread"_sv, "one"_sv, "fix"_sv, "emotion"_sv,
    "extend"_sv, "brick"_sv, "sponsor"_sv, "tired"_sv, "derive"_sv, "involve"_sv, "host"_sv, "mix"_sv, "soda"_sv,
    "mail"_sv, "winter"_sv, "lend"_sv, "slim"_sv, "casual"_sv, "crystal"_sv, "pupil"_sv, "tail"_sv, "air"_sv,
    "fancy"_sv, "note"_sv, "response"_sv, "concert"_sv, "wrestle"_sv, "resemble"_sv, "sadness"_sv, "twin"_sv,
    "defense"_sv, "lady"_sv, "pony"_sv, "outdoor"_sv, "escape"_sv, "viable"_sv, "drum"_sv, "boost"_sv, "rare"_sv,
    "ripple"_sv, "soon"_sv, "isolate"_sv, "crazy"_sv, "card"_sv, "phone"_sv, "grant"_sv, "among"_sv, "dizzy"_sv,
    "muffin"_sv, "rifle"_sv, "reform"_sv, "evidence"_sv, "banana"_sv, "opinion"_sv, "bounce"_sv, "choose"_sv,
    "razor"_sv, "knife"_sv, "lobster"_sv, "exotic"_sv, "relax"_sv, "enough"_sv, "tiny"_sv, "gold"_sv, "atom"_sv,
    "shallow"_sv, "grace"_sv, "govern"_sv, "vapor"_sv, "clog"_sv, "venture"_sv, "essay"_sv, "hawk"_sv, "undo"_sv,
    "dust"_sv, "enable"_sv, "future"_sv, "shell"_sv, "forum"_sv, "average"_sv, "peasant"_sv, "color"_sv, "juice"_sv,
    "tobacco"_sv, "awful"_sv, "upset"_sv, "session"_sv, "nothing"_sv, "boil"_sv, "approve"_sv, "sheriff"_sv, "type"_sv,
    "general"_sv, "joke"_sv, "rice"_sv, "need"_sv, "casino"_sv, "medal"_sv, "barely"_sv, "piece"_sv, "job"_sv,
    "news"_sv, "swap"_sv, "moral"_sv, "uncle"_sv, "junior"_sv, "amateur"_sv, "solve"_sv, "wide"_sv, "wheel"_sv,
    "expect"_sv, "thing"_sv, "erode"_sv, "cheap"_sv, "harvest"_sv, "rough"_sv, "true"_sv, "cereal"_sv, "improve"_sv,
    "chair"_sv, "praise"_sv, "little"_sv, "consider"_sv, "split"_sv, "mind"_sv, "party"_sv, "off"_sv, "actual"_sv,
    "chat"_sv, "blush"_sv, "proud"_sv, "resist"_sv, "glow"_sv, "flavor"_sv, "view"_sv, "during"_sv, "favorite"_sv,
    "perfect"_sv, "narrow"_sv, "success"_sv, "nature"_sv, "follow"_sv, "cloth"_sv, "donkey"_sv, "uniform"_sv,
    "steel"_sv, "youth"_sv, "mother"_sv, "vanish"_sv, "salad"_sv, "beyond"_sv, "area"_sv, "flat"_sv, "broccoli"_sv,
    "armor"_sv, "elbow"_sv, "alley"_sv, "submit"_sv, "burger"_sv, "jewel"_sv, "night"_sv, "firm"_sv, "advance"_sv,
    "custom"_sv, "vivid"_sv, "palm"_sv, "arena"_sv, "assume"_sv, "despair"_sv, "gown"_sv, "merry"_sv, "auto"_sv,
    "curious"_sv, "together"_sv, "surprise"_sv, "frost"_sv, "wonder"_sv, "crater"_sv, "share"_sv, "utility"_sv,
    "renew"_sv, "inspire"_sv, "robot"_sv, "street"_sv, "stumble"_sv, "noise"_sv, "minimum"_sv, "tooth"_sv, "foster"_sv,
    "river"_sv, "device"_sv, "code"_sv, "helmet"_sv, "hamster"_sv, "know"_sv, "outer"_sv, "sting"_sv, "balcony"_sv,
    "tragic"_sv, "ordinary"_sv, "spray"_sv, "bind"_sv, "young"_sv, "pumpkin"_sv, "suspect"_sv, "waste"_sv, "engine"_sv,
    "dress"_sv, "furnace"_sv, "lab"_sv, "length"_sv, "muscle"_sv, "mutual"_sv, "express"_sv, "october"_sv,
    "giraffe"_sv, "holiday"_sv, "canoe"_sv, "denial"_sv, "morning"_sv, "nuclear"_sv, "achieve"_sv, "prepare"_sv,
    "try"_sv, "dose"_sv, "rug"_sv, "army"_sv, "elite"_sv, "garden"_sv, "reject"_sv, "grief"_sv, "give"_sv, "excuse"_sv,
    "couple"_sv, "inherit"_sv, "ball"_sv, "minor"_sv, "treat"_sv, "tortoise"_sv, "cinnamon"_sv, "hill"_sv, "sort"_sv,
    "country"_sv, "laptop"_sv, "latin"_sv, "decade"_sv, "uphold"_sv, "seed"_sv, "kid"_sv, "wage"_sv, "patrol"_sv,
    "buyer"_sv, "clown"_sv, "amount"_sv, "horn"_sv, "wasp"_sv, "vicious"_sv, "wood"_sv, "skirt"_sv, "gate"_sv,
    "evolve"_sv, "empty"_sv, "wealth"_sv, "fame"_sv, "shoulder"_sv, "until"_sv, "lonely"_sv, "image"_sv, "there"_sv,
    "wild"_sv, "hungry"_sv, "elder"_sv, "estate"_sv, "step"_sv, "fabric"_sv, "cute"_sv, "agent"_sv, "ethics"_sv,
    "about"_sv, "december"_sv, "detect"_sv, "rookie"_sv, "horror"_sv, "race"_sv, "speak"_sv, "nut"_sv, "equip"_sv,
    "mango"_sv, "gadget"_sv, "address"_sv, "verify"_sv, "desk"_sv, "solid"_sv, "meadow"_sv, "define"_sv, "bulb"_sv,
    "token"_sv, "nest"_sv, "kangaroo"_sv, "swift"_sv, "someone"_sv, "path"_sv, "caught"_sv, "this"_sv, "venue"_sv,
    "alpha"_sv, "tell"_sv, "romance"_sv, "pair"_sv, "educate"_sv, "polar"_sv, "chest"_sv, "puppy"_sv, "load"_sv,
    "rural"_sv, "picnic"_sv, "film"_sv, "bean"_sv, "reunion"_sv, "source"_sv, "because"_sv, "churn"_sv, "whip"_sv,
    "cool"_sv, "faculty"_sv, "trick"_sv, "useless"_sv, "cube"_sv, "bicycle"_sv, "attack"_sv, "pause"_sv, "diamond"_sv,
    "excite"_sv, "unknown"_sv, "noodle"_sv, "marriage"_sv, "rival"_sv, "cycle"_sv, "hero"_sv, "term"_sv, "bacon"_sv,
    "gloom"_sv, "climb"_sv, "process"_sv, "eager"_sv, "cupboard"_sv, "bunker"_sv, "patch"_sv, "silent"_sv, "rubber"_sv,
    "obtain"_sv, "quote"_sv, "you"_sv, "cactus"_sv, "vacant"_sv, "soft"_sv, "plug"_sv, "music"_sv, "leaf"_sv, "old"_sv,
    "unaware"_sv, "van"_sv, "deliver"_sv, "notice"_sv, "stone"_sv, "rather"_sv, "lake"_sv, "kind"_sv, "remember"_sv,
    "human"_sv, "coast"_sv, "truck"_sv, "divorce"_sv, "attract"_sv, "annual"_sv, "spy"_sv, "drama"_sv, "all"_sv,
    "focus"_sv, "sniff"_sv, "sport"_sv, "humble"_sv, "asset"_sv, "possible"_sv, "art"_sv, "employ"_sv, "awesome"_sv,
    "island"_sv, "tunnel"_sv, "dynamic"_sv, "quality"_sv, "post"_sv, "shadow"_sv, "orchard"_sv, "net"_sv, "sure"_sv,
    "adult"_sv, "elegant"_sv, "attitude"_sv, "cannon"_sv, "penalty"_sv, "dish"_sv, "member"_sv, "also"_sv, "radio"_sv,
    "pigeon"_sv, "crawl"_sv, "three"_sv, "ten"_sv, "hood"_sv, "sugar"_sv, "nasty"_sv, "erupt"_sv, "claim"_sv,
    "base"_sv, "huge"_sv, "lyrics"_sv, "exist"_sv, "ski"_sv, "notable"_sv, "pledge"_sv, "sauce"_sv, "movie"_sv,
    "valve"_sv, "ignore"_sv, "whale"_sv, "space"_sv, "endless"_sv, "motion"_sv, "just"_sv, "cause"_sv, "barrel"_sv,
    "weasel"_sv, "mechanic"_sv, "dune"_sv, "myth"_sv, "fly"_sv, "festival"_sv, "goat"_sv, "breeze"_sv, "thrive"_sv,
    "affair"_sv, "segment"_sv, "liberty"_sv, "oppose"_sv, "nose"_sv, "feature"_sv, "order"_sv, "pencil"_sv, "main"_sv,
    "tribe"_sv, "siege"_sv, "number"_sv, "gauge"_sv, "guilt"_sv, "over"_sv, "install"_sv, "history"_sv, "cake"_sv,
    "appear"_sv, "chicken"_sv, "grocery"_sv, "obscure"_sv, "cook"_sv, "hire"_sv, "clay"_sv, "question"_sv, "tiger"_sv,
    "comfort"_sv, "alarm"_sv, "front"_sv, "shoe"_sv, "donor"_sv, "maid"_sv, "enforce"_sv, "slam"_sv, "ranch"_sv,
    "fold"_sv, "aware"_sv, "envelope"_sv, "sing"_sv, "gap"_sv, "damage"_sv, "fan"_sv, "sand"_sv, "come"_sv,
    "trophy"_sv, "region"_sv, "husband"_sv, "immense"_sv, "sausage"_sv, "leave"_sv, "width"_sv, "twelve"_sv, "best"_sv,
    "dial"_sv, "dirt"_sv, "bus"_sv, "organ"_sv, "dad"_sv, "jazz"_sv, "coil"_sv, "genre"_sv, "mansion"_sv, "sustain"_sv,
    "melt"_sv, "before"_sv, "dwarf"_sv, "letter"_sv, "match"_sv, "fashion"_sv, "hole"_sv, "naive"_sv, "rail"_sv,
    "wrap"_sv, "boss"_sv, "observe"_sv, "tumble"_sv, "special"_sv, "license"_sv, "arrive"_sv, "rib"_sv, "hair"_sv,
    "shine"_sv, "behave"_sv, "next"_sv, "below"_sv, "exhibit"_sv, "shy"_sv, "liquid"_sv, "fury"_sv, "goddess"_sv,
    "chaos"_sv, "wear"_sv, "spot"_sv, "oxygen"_sv, "adjust"_sv, "pipe"_sv, "pelican"_sv, "elevator"_sv,
    };

    return ids;
}

wordlist_t& ::bip0039::wordlistRuntimeShuffle()
{
    static optional<wordlist_t> ids;

    if (!ids)
    {
        ids = wordlist();
        std::random_shuffle ( ids->begin(), ids->end(), [](auto&& i) { return RNG.nextu(i); });
    }

    return *ids;
}